# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Digital manuscript facsimiles'
tagline:          'Openly licensed  data and images'
description:      'Images, catalogs and data sets modelling manuscripts.'



baseurl: '/mss/'


author:
  name:           'Neel Smith'
 

paginate:         5

github:
  repo:           https://github.com/openmss/mss

links:
  - title: Open Manuscript initiative
    url: http://openmss.github.io
    external: true
  - title: Github repository for this project
    url: https://github.com/openmss/mss
    external: true
