# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            'Digital manuscripts'
tagline:          'Openly licensed  data and images'
description:      'Images, catalogs and data sets modelling manuscripts.'



baseurl: '/mss/'


author:
  name:           'Neel Smith'
 

paginate:         5

github:
  repo:           https://github.com/openpaleography/mss

version:          0.12.0

links:
  - title: Open Paleography
    url: http://openpaleography.github.io
    external: true
  - title: Github project
    url: https://github.com/openpaleography/mss
    external: true
